version: "3"

name: hottesttechnologies

services:
  postgres:
    container_name: hottesttechnologies-postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hottesttechnologies
    expose:
      - "5432"
    ports:
      - "5432:5433" # respect prescient's ports
    command: -p 5433
